export const banner = {
  title: "BLOGS",
  image: "/assets/images/projects/banner.jpg",
};
export const blogs = [
  {
    id: 1,
    title: "How Advanced Door Solutions Improve Facility Safety.",
    date: "22-02-2026",
    desc: "Explore how advanced industrial door systems enhance safety, security, and operational efficiency across modern facilities.",
    img: "/assets/images/blog/blog-dummy-img.jpg",
    link: "/blogs/how-advanced-door-solutions-improve-facility-safety",
    category: "Industry",
    trending: true,
    mainDesc: "Advanced door systems play a vital role in maintaining safety standards across warehouses, manufacturing plants, and industrial facilities. From access control to fire protection and automation, these systems contribute to secure and efficient operations.",
    galleryImgs: ["/images/blog/blog-1-1.jpg", "/images/blog/blog-1-2.jpg"],
    subDesc1: "Modern facilities increasingly rely on intelligent door technologies to improve safety and reduce operational risks.",
    subDesc2: "Features such as automation, fire resistance, and integrated access systems help businesses maintain compliance and protect personnel.",
  },
  {
    id: 2,
    title: "Transforming Efficiency in Modern Warehousing.",
    date: "22-02-2025",
    desc: "Learn how innovative warehousing infrastructure and automation improve logistics performance and productivity.",
    img: "/assets/images/blog/blog-thumb-1.jpg",
    link: "/blogs/transforming-efficiency-in-modern-warehousing",
    category: "Industry",
    trending: false,
    mainDesc: "Modern warehousing depends on optimized layouts, intelligent storage systems, and automated workflows to maintain efficiency and scalability.",
    galleryImgs: ["/images/blog/blog-2-1.jpg", "/images/blog/blog-2-2.jpg"],
    subDesc1: "Efficient warehouse systems help streamline inventory movement and reduce delays.",
    subDesc2: "Smart logistics infrastructure enables faster processing and improved operational visibility.",
  },
  {
    id: 3,
    title: "Why Fire & Smoke Curtains Are Critical For Today’s Building Safety Standards",
    date: "22-02-2025",
    desc: "Understand the importance of fire and smoke curtain systems in meeting modern building safety requirements.",
    img: "/assets/images/blog/blog-thumb-2.jpg",
    link: "/blogs/why-fire-smoke-curtains-are-critical-for-todays-building-safety-standards",
    category: "Technology",
    trending: false,
    mainDesc: "Fire and smoke curtains provide essential compartmentation during emergencies, helping to limit smoke spread and support safe evacuation.",
    galleryImgs: ["/images/blog/blog-3-1.jpg", "/images/blog/blog-3-2.jpg"],
    subDesc1: "Building regulations increasingly demand advanced fire protection systems.",
    subDesc2: "Fire and smoke curtains offer discreet yet highly effective protection for commercial and industrial spaces.",
  },
  {
    id: 4,
    title: "The Backbone of Seamless Logistics Operations",
    date: "22-02-2025",
    desc: "Discover the infrastructure and systems that support efficient logistics and supply chain operations.",
    img: "/assets/images/blog/blog-thumb-3.jpg",
    link: "/blogs/the-backbone-of-seamless-logistics-operations",
    category: "Market",
    trending: false,
    mainDesc: "Logistics operations depend on integrated infrastructure, reliable loading systems, and optimized facility design to maintain seamless workflows.",
    galleryImgs: ["/images/blog/blog-4-1.jpg", "/images/blog/blog-4-2.jpg"],
    subDesc1: "Seamless logistics relies on coordinated systems that reduce downtime and improve throughput.",
    subDesc2: "Modern infrastructure investments strengthen supply chain resilience and operational flexibility.",
  },
  {
    id: 5,
    title: "Integrating Safety, Automation & Access Solutions",
    date: "22-02-2025",
    desc: "See how combining safety, automation, and access technologies creates smarter facilities.",
    img: "/assets/images/blog/blog-thumb-4.jpg",
    link: "/blogs/integrating-safety-automation-access-solutions",
    category: "Knowledge",
    trending: false,
    mainDesc: "Integrated facility solutions combine automation, access control, and safety technologies to create secure and efficient environments.",
    galleryImgs: ["/images/blog/blog-5-1.jpg", "/images/blog/blog-5-2.jpg"],
    subDesc1: "Connected systems improve monitoring, access management, and operational efficiency.",
    subDesc2: "A unified approach to safety and automation helps future-proof modern buildings and industrial spaces.",
  },
  {
    id: 6,
    title: "How Advanced Door Solutions Improve Facility Safety.",
    date: "22-02-2025",
    desc: "Explore how advanced industrial door systems enhance safety, security, and operational efficiency across modern facilities.",
    img: "/assets/images/blog/blog-dummy-img.jpg",
    link: "/blogs/how-advanced-door-solutions-improve-facility-safety",
    category: "Industry",
    trending: true,
    mainDesc: "Advanced door systems play a vital role in maintaining safety standards across warehouses, manufacturing plants, and industrial facilities. From access control to fire protection and automation, these systems contribute to secure and efficient operations.",
    galleryImgs: ["/images/blog/blog-1-1.jpg", "/images/blog/blog-1-2.jpg"],
    subDesc1: "Modern facilities increasingly rely on intelligent door technologies to improve safety and reduce operational risks.",
    subDesc2: "Features such as automation, fire resistance, and integrated access systems help businesses maintain compliance and protect personnel.",
  },
  {
    id: 7,
    title: "Transforming Efficiency in Modern Warehousing.",
    date: "22-02-2025",
    desc: "Learn how innovative warehousing infrastructure and automation improve logistics performance and productivity.",
    img: "/assets/images/blog/blog-thumb-1.jpg",
    link: "/blogs/transforming-efficiency-in-modern-warehousing",
    category: "Industry",
    trending: false,
    mainDesc: "Modern warehousing depends on optimized layouts, intelligent storage systems, and automated workflows to maintain efficiency and scalability.",
    galleryImgs: ["/images/blog/blog-2-1.jpg", "/images/blog/blog-2-2.jpg"],
    subDesc1: "Efficient warehouse systems help streamline inventory movement and reduce delays.",
    subDesc2: "Smart logistics infrastructure enables faster processing and improved operational visibility.",
  },
  {
    id: 8,
    title: "Why Fire & Smoke Curtains Are Critical For Today’s Building Safety Standards",
    date: "22-02-2025",
    desc: "Understand the importance of fire and smoke curtain systems in meeting modern building safety requirements.",
    img: "/assets/images/blog/blog-thumb-2.jpg",
    link: "/blogs/why-fire-smoke-curtains-are-critical-for-todays-building-safety-standards",
    category: "Technology",
    trending: false,
    mainDesc: "Fire and smoke curtains provide essential compartmentation during emergencies, helping to limit smoke spread and support safe evacuation.",
    galleryImgs: ["/images/blog/blog-3-1.jpg", "/images/blog/blog-3-2.jpg"],
    subDesc1: "Building regulations increasingly demand advanced fire protection systems.",
    subDesc2: "Fire and smoke curtains offer discreet yet highly effective protection for commercial and industrial spaces.",
  },
  {
    id: 9,
    title: "The Backbone of Seamless Logistics Operations",
    date: "22-02-2025",
    desc: "Discover the infrastructure and systems that support efficient logistics and supply chain operations.",
    img: "/assets/images/blog/blog-thumb-3.jpg",
    link: "/blogs/the-backbone-of-seamless-logistics-operations",
    category: "Market",
    trending: false,
    mainDesc: "Logistics operations depend on integrated infrastructure, reliable loading systems, and optimized facility design to maintain seamless workflows.",
    galleryImgs: ["/images/blog/blog-4-1.jpg", "/images/blog/blog-4-2.jpg"],
    subDesc1: "Seamless logistics relies on coordinated systems that reduce downtime and improve throughput.",
    subDesc2: "Modern infrastructure investments strengthen supply chain resilience and operational flexibility.",
  },
  {
    id: 10,
    title: "Integrating Safety, Automation & Access Solutions",
    date: "22-02-2025",
    desc: "See how combining safety, automation, and access technologies creates smarter facilities.",
    img: "/assets/images/blog/blog-thumb-4.jpg",
    link: "/blogs/integrating-safety-automation-access-solutions",
    category: "Knowledge",
    trending: false,
    mainDesc: "Integrated facility solutions combine automation, access control, and safety technologies to create secure and efficient environments.",
    galleryImgs: ["/images/blog/blog-5-1.jpg", "/images/blog/blog-5-2.jpg"],
    subDesc1: "Connected systems improve monitoring, access management, and operational efficiency.",
    subDesc2: "A unified approach to safety and automation helps future-proof modern buildings and industrial spaces.",
  },
];
